export const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    me: '/auth/me',
    update: '/auth/me',
    logout: '/auth/logout',
    changePassword: '/auth/change-password',
  },
  admin: {
    dashboard: '/admin/dashboard',
    branches: {
      list: '/admin/branches',
      create: '/admin/branches',
      detail: (id) => `/admin/branches/${id}`,
      update: (id) => `/admin/branches/${id}`,
      status: (id) => `/admin/branches/${id}/status`,
      resetPassword: (id) => `/admin/branches/${id}/reset-password`,
      remove: (id) => `/admin/branches/${id}`,
    },
    company: {
      get: '/admin/company',
      update: '/admin/company',
    },
    policies: {
      list: '/admin/policies',
      create: '/admin/policies',
      detail: (id) => `/admin/policies/${id}`,
      update: (id) => `/admin/policies/${id}`,
      remove: (id) => `/admin/policies/${id}`,
    },
    taxProfit: {
      meta: '/admin/tax-profit/meta',
      products: '/admin/tax-profit/products',
      defaults: '/admin/tax-profit/defaults',
      bulkProfit: '/admin/tax-profit/bulk-profit',
      bulkTax: '/admin/tax-profit/bulk-tax',
    },
    settings: {
      devices: '/admin/settings/devices',
      deviceStatus: (id) => `/admin/settings/devices/${id}/status`,
      currency: '/admin/settings/currency',
    },
    invoices: {
      list: '/admin/invoices',
      summary: '/admin/invoices/summary',
      detail: (id) => `/admin/invoices/${id}`,
    },
    leaves: {
      list: '/admin/leaves',
      decide: (id) => `/admin/leaves/${id}/decide`,
    },
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    read: (id) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
    remove: (id) => `/notifications/${id}`,
  },
  dashboard: {
    overview: '/inventory/dashboard/overview',
    alerts: '/inventory/dashboard/alerts',
    stockGraph: '/inventory/dashboard/stock-graph',
    summary: '/inventory/dashboard/overview',
  },
  branch: {
    dashboard: '/branch/dashboard',
    staff: {
      list: '/branch/staff',
      export: '/branch/staff/export',
      create: '/branch/staff',
      detail: (id) => `/branch/staff/${id}`,
      update: (id) => `/branch/staff/${id}`,
      status: (id) => `/branch/staff/${id}/status`,
      reallocate: (id) => `/branch/staff/${id}/reallocate-hardware`,
      delete: (id) => `/branch/staff/${id}`,
    },
    designations: {
      list: '/branch/designations',
      create: '/branch/designations',
    },
    sales: {
      list: '/branch/sales',
      refund: (id) => `/branch/sales/${id}/refund`,
    },
    discounts: {
      list: '/branch/discounts',
      create: '/branch/discounts',
      update: (id) => `/branch/discounts/${id}`,
      delete: (id) => `/branch/discounts/${id}`,
    },
    resources: {
      hardware: {
        list: '/branch/resources/hardware',
        create: '/branch/resources/hardware',
        update: (id) => `/branch/resources/hardware/${id}`,
        delete: (id) => `/branch/resources/hardware/${id}`,
      },
      scales: {
        list: '/branch/resources/scales',
        create: '/branch/resources/scales',
        update: (id) => `/branch/resources/scales/${id}`,
        delete: (id) => `/branch/resources/scales/${id}`,
      },
      variantTypes: {
        list: '/branch/resources/variant-types',
        create: '/branch/resources/variant-types',
        detail: (id) => `/branch/resources/variant-types/${id}`,
        update: (id) => `/branch/resources/variant-types/${id}`,
        delete: (id) => `/branch/resources/variant-types/${id}`,
      },
      variantValues: {
        list: '/branch/resources/variant-values',
        create: '/branch/resources/variant-values',
        detail: (id) => `/branch/resources/variant-values/${id}`,
        update: (id) => `/branch/resources/variant-values/${id}`,
        delete: (id) => `/branch/resources/variant-values/${id}`,
      },
    },
    activityLogs: {
      list: '/branch/activity-logs',
    },
    priceRule: '/branch/inventory/price-rule',
  },
  products: {
    list: '/inventory/products',
    create: '/inventory/products',
    bundles: '/inventory/products/bundles',
    import: '/inventory/products/import',
    export: '/inventory/products/export',
    scan: '/inventory/products/scan',
    detail: (id) => `/inventory/products/${id}`,
    deleteInfo: (id) => `/inventory/products/${id}/delete-info`,
    update: (id) => `/inventory/products/${id}`,
    remove: (id) => `/inventory/products/${id}`,
    barcode: (id) => `/inventory/products/${id}/barcode`,
    categories: '/inventory/products/categories',
    subcategories: '/inventory/products/subcategories',
    category: (id) => `/inventory/products/categories/${id}`,
    taxes: '/inventory/products/taxes',
    taxProfitDefaults: '/inventory/products/tax-profit-defaults',
    offers: '/inventory/products/offers',
  },
  // @deprecated prefer products.* — kept for older slices
  categories: {
    list: '/inventory/products/categories',
    create: '/inventory/products/categories',
    update: (id) => `/inventory/products/categories/${id}`,
  },
  items: {
    list: '/inventory/products',
    create: '/inventory/products',
    update: (id) => `/inventory/products/${id}`,
    import: '/inventory/products/import',
  },
  control: {
    summary: '/inventory/control/summary',
    dailyPrices: '/inventory/control/daily-prices',
    dailyPrice: (id) => `/inventory/control/daily-prices/${id}`,
    thresholds: '/inventory/control/thresholds',
    threshold: (id) => `/inventory/control/thresholds/${id}`,
    alerts: '/inventory/control/alerts',
    export: '/inventory/control/export',
    import: '/inventory/control/import',
    priceRule: '/inventory/control/price-rule',
    stockIn: '/inventory/control/stock-in',
    stockInFromOrder: '/inventory/control/stock-in/from-order',
    stockOut: '/inventory/control/stock-out',
    adjustments: '/inventory/control/adjustments',
    adjustmentLedger: '/inventory/control/adjustment-ledger',
    adjustment: (id) => `/inventory/control/adjustments/${id}`,
    damaged: '/inventory/control/damaged',
    damagedItem: (id) => `/inventory/control/damaged/${id}`,
    expired: '/inventory/control/expired',
    expiredItem: (id) => `/inventory/control/expired/${id}`,
    others: '/inventory/control/others',
    otherItem: (id) => `/inventory/control/others/${id}`,
    transfers: '/inventory/control/transfers',
  },
  lookups: {
    employees: '/inventory/lookups/employees',
    branches: '/inventory/lookups/branches',
  },
  stockIn: {
    list: '/inventory/control/stock-in',
    create: '/inventory/control/stock-in',
  },
  stockOut: {
    list: '/inventory/control/stock-out',
  },
  adjustments: {
    list: '/inventory/control/adjustments',
    create: '/inventory/control/adjustments',
  },
  damaged: {
    list: '/inventory/control/damaged',
    create: '/inventory/control/damaged',
  },
  expired: {
    list: '/inventory/control/expired',
  },
    suppliers: {
    list: '/inventory/suppliers',
    create: '/inventory/suppliers',
    update: (id) => `/inventory/suppliers/${id}`,
    status: (id) => `/inventory/suppliers/${id}/status`,
    remove: (id) => `/inventory/suppliers/${id}`,
  },
  orders: {
    list: '/inventory/purchase-orders',
    create: '/inventory/purchase-orders',
    detail: (id) => `/inventory/purchase-orders/${id}`,
    history: (id) => `/inventory/purchase-orders/${id}/history`,
    print: (id) => `/inventory/purchase-orders/${id}/print`,
    approve: (id) => `/inventory/purchase-orders/${id}/approve`,
    sendSms: (id) => `/inventory/purchase-orders/${id}/send-sms`,
    cancel: (id) => `/inventory/purchase-orders/${id}/cancel`,
  },
}
